### ISSUE TITLE
sqlitebrowser freezes

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1178]
### Details for the issue

I'm having problems with the current git version. It worked well using a cloned repository from 2017-10-02 13:58:30. When I downloaded a new copy from the latest version, the browser is getting frozen when working with the filter or when displaying a table. I've debugged the process and got these call stacks:

```
(gdb) thread apply all bt

Thread 6 (Thread 0x7fc60e38d700 (LWP 4516)):
#0  0x00007fc6323ca70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fc63155938c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fc63155949c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fc6332167cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fc6331bdb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fc632fda834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fc632fdf7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fc6320b96ba in start_thread (arg=0x7fc60e38d700) at pthread_create.c:333
#8  0x00007fc6323d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fc61cc75700 (LWP 4512)):
#0  0x00007fc6323ca70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fc63155938c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fc631559712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fc6257e69d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fc63157fbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc6320b96ba in start_thread (arg=0x7fc61cc75700) at pthread_create.c:333
#6  0x00007fc6323d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fc61d476700 (LWP 4510)):
#0  0x00007fc6323ca70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fc63155938c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fc63155949c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fc6315594d9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fc63157fbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc6320b96ba in start_thread (arg=0x7fc61d476700) at pthread_create.c:333
#6  0x00007fc6323d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fc61dc77700 (LWP 4509)):
#0  0x00007fc6323ca70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fc63155938c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fc63155949c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fc61dc7f28d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fc63157fbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc6320b96ba in start_thread (arg=0x7fc61dc77700) at pthread_create.c:333
#6  0x00007fc6323d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fc627f93700 (LWP 4508)):
#0  0x00007fc6323ca70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fc62f7ebc62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fc62f7ed8d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fc62b170889 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fc632fdf7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fc6320b96ba in start_thread (arg=0x7fc627f93700) at pthread_create.c:333
#6  0x00007fc6323d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7fc62b790740 (LWP 4507)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fc632fd78b8 in QBasicMutex::lockInternal() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00000000005551b0 in SqliteTableModel::data(QModelIndex const&, int) const ()
#3  0x00007fc633cf7d5d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fc62b1bcba6 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#5  0x00007fc633d4848b in QTableView::selectionChanged(QItemSelection const&, QItemSelection const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fc633d13ab1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fc6331eed2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fc633170d27 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fc633178e17 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fc633179e09 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007fc6331eed2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fc63326b0c4 in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fc633167c33 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00000000005538eb in SqliteTableModel::clearCache() ()
#15 0x000000000055846f in SqliteTableModel::setQuery(QString const&, bool) ()
#16 0x0000000000558cac in SqliteTableModel::buildQuery() ()
#17 0x00000000005596bd in SqliteTableModel::updateFilter(int, QString const&) ()
#18 0x00000000005148b3 in MainWindow::updateFilter(int, QString const&) ()
#19 0x00000000005f4bee in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#20 0x00007fc6331eed2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00000000005f36c3 in FilterTableHeader::filterChanged(int, QString) ()
#22 0x0000000000500467 in FilterTableHeader::inputChanged(QString const&) ()
#23 0x00000000005f49a9 in FilterTableHeader::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#24 0x00007fc6331eed2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00000000005f3662 in FilterLineEdit::delayedTextChanged(QString) ()
#26 0x00000000005d062b in FilterLineEdit::delayedSignalTimerTriggered() ()
#27 0x00000000005f47c5 in FilterLineEdit::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#28 0x00007fc6331eed2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007fc6331fb5c8 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007fc6331efbb3 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007fc633ab305c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007fc633ab8516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007fc6331c038b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fc6332155ed in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007fc633215af1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007fc631559197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fc6315593f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fc63155949c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fc6332167cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007fc6331bdb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fc6331c5bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00000000004d4cfb in main ()

```

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 16.04.3 LTS )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [X] Other: git 2017-10-11 18:41:06 SHA ID 973f97c1ebd3ebe060172fb2f2810a871c2d9da9

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just to confirm whether its an application or database issue, does it do this on all databases?  If you create a new database with a table and (say) 6 fields, does it do it then?
Is the database on a local drive or network drive?

**Comment by justinclift** [comment]
@mgrojo It might be something to do with the new multi-threaded code we added a few days ago for the data fetching part.

**Comment by MKleusberg** [comment]
Yeah, it definitely is. This is super-annoying because it all seems to depend on the Qt version. Not so much for the multi-threading bits but for how the table view is rendered and refreshed 😦 Will investigate it tomorrow.

**Comment by mgrojo** [comment]
@chrisjlocke Yes, it happens with a minimal database stored in local disk

@chrisjlocke, @MKleusberg I reproduce it very easily. If you need help for testing, because in your environment is not reproduced, just ask. Thank you for the quick response.

**Comment by chrisjlocke** [comment]
Isn't Qt part of the DB4S package? What I mean is, everyone should be using the same Qt version?

**Comment by justinclift** [comment]
Well, when DB4S is compiled it'll use whichever version of Qt it's provided with.  So on Windows we're using Qt 5.7 (not the latest) as that allows us to support XP for 32 bit bits.  For OSX we use Qt 5.9.1 (the latest) as there's no real use in using an older version.  And the various Linux distributions each have their own provided Qt versions too.

So, we generally limit ourselves to using features from Qt 5.5 at latest (not newer) in order to keep ourselves compatible with a fairly wide range of things.

**Comment by chrisjlocke** [comment]
Aah, gotcha. Thanks

**Comment by MKleusberg** [comment]
Sorry, took a bit longer :wink: Can you compile and try again using the latest commit, @mgrojo? I hope that fixes your problem or at least yields a different stack trace if there are more issues like this.

**Comment by mgrojo** [comment]
@MKleusberg, unfortunately it is still happening in my environment. This is the new backtrace:

```
(gdb) thread apply all bt

Thread 6 (Thread 0x7f4312859700 (LWP 6180)):
#0  0x00007f433a8b470d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f4339a4338c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f4339a4349c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f433b7007cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f433b6a7b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f433b4c4834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f433b4c97be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f433a5a36ba in start_thread (arg=0x7f4312859700) at pthread_create.c:333
#8  0x00007f433a8c03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f43250cd700 (LWP 6176)):
#0  0x00007f433a8b470d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f4339a4338c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f4339a43712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f432dcd09d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f4339a69bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f433a5a36ba in start_thread (arg=0x7f43250cd700) at pthread_create.c:333
#6  0x00007f433a8c03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f43258ce700 (LWP 6175)):
#0  0x00007f433a8b470d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f4339a4338c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f4339a4349c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f4339a434d9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f4339a69bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f433a5a36ba in start_thread (arg=0x7f43258ce700) at pthread_create.c:333
#6  0x00007f433a8c03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f43260cf700 (LWP 6173)):
#0  0x00007f433a8b470d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f4339a4338c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f4339a4349c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f43260d728d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007f4339a69bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f433a5a36ba in start_thread (arg=0x7f43260cf700) at pthread_create.c:333
#6  0x00007f433a8c03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f433047d700 (LWP 6172)):
#0  0x00007f433a8b470d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f4337cd5c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f4337cd78d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f433365a889 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f433b4c97be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f433a5a36ba in start_thread (arg=0x7f433047d700) at pthread_create.c:333
#6  0x00007f433a8c03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f4333c7a740 (LWP 6171)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f433b4c18b8 in QBasicMutex::lockInternal() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x0000000000556070 in SqliteTableModel::data(QModelIndex const&, int) const ()
#3  0x00007f433c1e1d5d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007f43336a6ba6 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#5  0x00007f433c23248b in QTableView::selectionChanged(QItemSelection const&, QItemSelection const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f433c1fdab1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007f433b6d8d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f433b65ad27 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f433b662e17 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f433b663e09 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f433b6d8d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f433b7550c4 in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f433b651c33 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x000000000055478b in SqliteTableModel::clearCache() ()
#15 0x000000000055931f in SqliteTableModel::setQuery(QString const&, bool) ()
#16 0x0000000000559b5c in SqliteTableModel::buildQuery() ()
#17 0x000000000055a56d in SqliteTableModel::updateFilter(int, QString const&) ()
#18 0x0000000000515373 in MainWindow::updateFilter(int, QString const&) ()
#19 0x00000000005f5ae5 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#20 0x00007f433b6d8d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00000000005f4553 in FilterTableHeader::filterChanged(int, QString) ()
#22 0x0000000000500db7 in FilterTableHeader::inputChanged(QString const&) ()
#23 0x00000000005f5899 in FilterTableHeader::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#24 0x00007f433b6d8d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00000000005f44f2 in FilterLineEdit::delayedTextChanged(QString) ()
#26 0x00000000005d14bb in FilterLineEdit::delayedSignalTimerTriggered() ()
#27 0x00000000005f56b5 in FilterLineEdit::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#28 0x00007f433b6d8d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f433b6e55c8 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007f433b6d9bb3 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007f433bf9d05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f433bfa2516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f433b6aa38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007f433b6ff5ed in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007f433b6ffaf1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007f4339a43197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007f4339a433f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007f4339a4349c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007f433b7007cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007f433b6a7b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007f433b6afbec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00000000004d564b in main ()

```

```

**Comment by MKleusberg** [comment]
Ok, this definitely looks like it can be fixed 😄 Can you try again with the commit I've just pushed?

**Comment by mgrojo** [comment]
@MKleusberg , congratulations! You've fixed it.

**Comment by MKleusberg** [comment]
Cool :smile: If you notice any other problems with the multi-threading (like freezes in other parts of the program), please open an other issue if you have the time. It's way harder than expected to get this right, especially when addressing many different Qt versions.
